### ISSUE TITLE
reblex_register_block_patterns function override post ID in media screen

### ISSUE THREAD

**Issue by MarieComet** [audrasjb/reusable-blocks-extended#1]
The function `reblex_register_block_patterns`, which register a pattern for each reusable block transformed in pattern, override the global post ID in the "add new media" screen.

When uploading a media in Medias => Add new, the media "take" the post ID of the first Reusable block published.
The consequence is that this media is uploaded in the wrong folder.
If the first block was published on October 2011, the new media is uploaded in wp-content/uploads/2011/10/

It's visible in media new screen source code. In this example, 57821 is the post ID of the reusable block, which shouldn't be here.
![media-new](https://user-images.githubusercontent.com/7976501/166238488-0f309b14-efa0-4cad-bb5b-14f92f8e43dc.png)

Video to reproduce the bug : 

https://user-images.githubusercontent.com/7976501/166238594-86e07749-88ff-47e9-bfe0-abfbab4bbd68.mp4

**Comment by audrasjb** [comment]
Fixed!

**Comment by MarieComet** [comment]
Thanks @audrasjb
