### ISSUE TITLE
reblex_reusable_screen_add_column is overriding columns added by show_admin_column

### ISSUE THREAD

**Issue by MarieComet** [audrasjb/reusable-blocks-extended#4]
The function `reblex_reusable_screen_add_column` return only custom columns added by the plugin, overriding columns automatically added by `show_admin_column` param used in `register_taxonomy`.

For example, I want to add a custom taxonomy to the wp_block post type : 

```
$args = [
    'labels'                     => [
        'name'                       => _x( 'Types', 'Taxonomy General Name', 'ek-gut' ),
        'singular_name'              => _x( 'Type', 'Taxonomy Singular Name', 'ek-gut' ),
        'menu_name'                  => __( 'Types', 'ek-gut' )
    ],
    'show_admin_column'          => true,
    'show_in_rest'               => true
];
register_taxonomy( 'wp_block_type', [ 'wp_block' ], $args );
```
The `wp_block_type` terms should be visible in the blocks list view, but actually they don't because the function which register custom columns do not merge existing columns before return : 
```
function reblex_reusable_screen_add_column( $columns ) {
	$columns = array(
		'cb' => '<input type="checkbox" />',
		'title' => esc_html__( 'Block title', 'reusable-blocks-extended' ),
		'reblex-reusable-instances' => esc_html__( 'Used in', 'reusable-blocks-extended' ),
		'reblex-reusable-preview' => esc_html__( 'Usage', 'reusable-blocks-extended' ),
		'reblex-reusable-conversion' => esc_html__( 'Pattern conversion', 'reusable-blocks-extended' ),
		'reblex-date-modified' => esc_html__( 'Last modified', 'reusable-blocks-extended' )
	);
	return $columns;
}
```

To fix this, would you consider to merge existing columns with your columns before returning them ?

Please see the following pull request : https://github.com/audrasjb/reusable-blocks-extended/pull/3

**Comment by audrasjb** [comment]
Fixed in #3
