### ISSUE TITLE
Deprecation: block categories

### ISSUE THREAD

**Issue by audrasjb** [audrasjb/reusable-blocks-extended#8]
Feedback from w.org: 

I’m also getting the following error that i believe is tied to reusable blocks: Deprecated: Hook block_categories is deprecated since version 5.8.0! Use block_categories_all instead. in /home/lrh8yxotlggk/public_html/wp-includes/functions.php on line 5754

**Comment by gturpin-dev** [comment]
Hi,

I cannot reproduce the error when I activate the plugin on a fresh install.

I also don't find any occurence of "block_categories" in the plugin.

So I think the issue can be closed as I believe the error do not come from this plugin.

**Comment by audrasjb** [comment]
I cannot reproduce it either. Closing as fixed.
